// <auto-generated />
using System;
using HospitalCalendar.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HospitalCalendar.EntityFramework.Migrations
{
    [DbContext(typeof(HospitalCalendarDbContext))]
    [Migration("20200415144242_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Anamnesis", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("PatientID")
                        .IsUnique();

                    b.ToTable("Anamneses");
                });

            modelBuilder.Entity("AppointmentChangeRequest", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppointmentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NewEndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NewStartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PreviousEndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PreviousStartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("AppointmentID");

                    b.ToTable("AppointmentChangeRequests");
                });

            modelBuilder.Entity("AppointmentChangeRequestNotification", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppointmentChangeRequestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SecretaryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("AppointmentChangeRequestID");

                    b.HasIndex("SecretaryID");

                    b.ToTable("AppointmentChangeRequestNotifications");
                });

            modelBuilder.Entity("AppointmentRequest", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PatientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProposedDoctorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RequesterID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("PatientID");

                    b.HasIndex("ProposedDoctorID");

                    b.HasIndex("RequesterID");

                    b.ToTable("AppointmentRequests");
                });

            modelBuilder.Entity("AppointmentRequestNotification", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppointmentRequestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SecretaryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("AppointmentRequestID");

                    b.HasIndex("SecretaryID");

                    b.ToTable("AppointmentRequestNotifications");
                });

            modelBuilder.Entity("CalendarEntry", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("CalendarEntries");

                    b.HasDiscriminator<string>("Discriminator").HasValue("CalendarEntry");
                });

            modelBuilder.Entity("Entry", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnamnesisID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DoctorID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("AnamnesisID");

                    b.HasIndex("DoctorID");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("EquipmentItem", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EquipmentTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoomID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("EquipmentTypeID");

                    b.HasIndex("RoomID");

                    b.ToTable("EquipmentItems");
                });

            modelBuilder.Entity("EquipmentType", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FreeAmount")
                        .HasColumnType("int");

                    b.Property<int>("InUseAmount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("EquipmentTypes");
                });

            modelBuilder.Entity("HospitalCalendar.Domain.Models.DoctorPatient", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DoctorId", "PatientId");

                    b.HasIndex("PatientId");

                    b.ToTable("DoctorsPatients");
                });

            modelBuilder.Entity("HospitalCalendar.Domain.Models.Specialization", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DoctorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SingleSpecialization")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DoctorID");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("Room", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("SurgeryNotification", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SecretaryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SurgeryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("SecretaryID");

                    b.HasIndex("SurgeryID");

                    b.ToTable("SurgeryNotifications");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("Appointment", b =>
                {
                    b.HasBaseType("CalendarEntry");

                    b.Property<Guid?>("DoctorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PatientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoomID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TypeID")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.HasIndex("RoomID");

                    b.HasIndex("TypeID");

                    b.HasDiscriminator().HasValue("Appointment");
                });

            modelBuilder.Entity("Renovation", b =>
                {
                    b.HasBaseType("CalendarEntry");

                    b.Property<bool>("ChangingLayout")
                        .HasColumnType("bit");

                    b.Property<bool>("ChangingRoomType")
                        .HasColumnType("bit");

                    b.Property<bool>("MovingEquipment")
                        .HasColumnType("bit");

                    b.Property<int>("NewRoomType")
                        .HasColumnType("int");

                    b.Property<Guid?>("RoomID")
                        .HasColumnName("Renovation_RoomID")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("RoomID");

                    b.HasDiscriminator().HasValue("Renovation");
                });

            modelBuilder.Entity("Doctor", b =>
                {
                    b.HasBaseType("User");

                    b.Property<TimeSpan>("WorkingHoursEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("WorkingHoursStart")
                        .HasColumnType("time");

                    b.HasDiscriminator().HasValue("Doctor");
                });

            modelBuilder.Entity("Manager", b =>
                {
                    b.HasBaseType("User");

                    b.HasDiscriminator().HasValue("Manager");
                });

            modelBuilder.Entity("Patient", b =>
                {
                    b.HasBaseType("User");

                    b.Property<string>("InsuranceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Patient");
                });

            modelBuilder.Entity("Secretary", b =>
                {
                    b.HasBaseType("User");

                    b.HasDiscriminator().HasValue("Secretary");
                });

            modelBuilder.Entity("Surgery", b =>
                {
                    b.HasBaseType("Appointment");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Surgery");
                });

            modelBuilder.Entity("Anamnesis", b =>
                {
                    b.HasOne("Patient", "Patient")
                        .WithOne("Anamnesis")
                        .HasForeignKey("Anamnesis", "PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppointmentChangeRequest", b =>
                {
                    b.HasOne("Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentID");
                });

            modelBuilder.Entity("AppointmentChangeRequestNotification", b =>
                {
                    b.HasOne("AppointmentChangeRequest", "AppointmentChangeRequest")
                        .WithMany()
                        .HasForeignKey("AppointmentChangeRequestID");

                    b.HasOne("Secretary", null)
                        .WithMany("AppointmentChangeRequestNotifications")
                        .HasForeignKey("SecretaryID");
                });

            modelBuilder.Entity("AppointmentRequest", b =>
                {
                    b.HasOne("Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID");

                    b.HasOne("Doctor", "ProposedDoctor")
                        .WithMany()
                        .HasForeignKey("ProposedDoctorID");

                    b.HasOne("Doctor", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterID");
                });

            modelBuilder.Entity("AppointmentRequestNotification", b =>
                {
                    b.HasOne("AppointmentRequest", "AppointmentRequest")
                        .WithMany()
                        .HasForeignKey("AppointmentRequestID");

                    b.HasOne("Secretary", null)
                        .WithMany("AppointmentRequestNotifications")
                        .HasForeignKey("SecretaryID");
                });

            modelBuilder.Entity("Entry", b =>
                {
                    b.HasOne("Anamnesis", "Anamnesis")
                        .WithMany("Entries")
                        .HasForeignKey("AnamnesisID");

                    b.HasOne("Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorID");
                });

            modelBuilder.Entity("EquipmentItem", b =>
                {
                    b.HasOne("EquipmentType", "EquipmentType")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeID");

                    b.HasOne("Room", "Room")
                        .WithMany("Equipment")
                        .HasForeignKey("RoomID");
                });

            modelBuilder.Entity("HospitalCalendar.Domain.Models.DoctorPatient", b =>
                {
                    b.HasOne("Doctor", "Doctor")
                        .WithMany("DoctorsPatients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Patient", "Patient")
                        .WithMany("DoctorsPatients")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalCalendar.Domain.Models.Specialization", b =>
                {
                    b.HasOne("Doctor", null)
                        .WithMany("Specializations")
                        .HasForeignKey("DoctorID");
                });

            modelBuilder.Entity("SurgeryNotification", b =>
                {
                    b.HasOne("Secretary", null)
                        .WithMany("SurgeryNotifications")
                        .HasForeignKey("SecretaryID");

                    b.HasOne("Surgery", "Surgery")
                        .WithMany()
                        .HasForeignKey("SurgeryID");
                });

            modelBuilder.Entity("Appointment", b =>
                {
                    b.HasOne("Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorID");

                    b.HasOne("Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID");

                    b.HasOne("Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomID");

                    b.HasOne("HospitalCalendar.Domain.Models.Specialization", "Type")
                        .WithMany()
                        .HasForeignKey("TypeID");
                });

            modelBuilder.Entity("Renovation", b =>
                {
                    b.HasOne("Room", null)
                        .WithMany("Renovations")
                        .HasForeignKey("RoomID");
                });
#pragma warning restore 612, 618
        }
    }
}
